config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount API => '/'

  namespace :admin do
    root to: 'users#index'
    resources :car_owners do
      resources :cars
      resources :emails
      resources :phones
    end

    resources :chains do
      member do
        post :update_sheet
      end
      resources :shops
      resources :discounts
      resources :sheets
      resources :sheet_settings
    end

    resources :settings, only: [:edit, :update]
  end

end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id         :integer          not null, primary key
#  address    :string
#  opening_at :time
#  closing_at :time
#  chain_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_shops_on_chain_id  (chain_id)
#

class Shop < ActiveRecord::Base
  belongs_to :chain
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  inherit_resources
  belongs_to :chain

  def create
    create! { collection_path }
  end

  def update
    update! { collection_path }
  end

  private

  def permitted_params
    params.permit!
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def shops_actions(resource)
    buttons = []
    buttons << link_to('Edit', edit_resource_path(resource), class: 'btn btn-default btn-sm')
    buttons << link_to('Delete', resource_path(resource), method: :delete, class: 'btn btn-danger btn-sm')
    buttons.join(' ').html_safe
  end
end

app/views/admin/shops/_form.html.slim
= simple_form_for [:admin, parent, resource], html: { class: 'form-horizontal' },
                            wrapper: :horizontal_form,
                            wrapper_mappings: {\
                              file: :horizontal_file_input\
                            } do |f|
  .well.btn-toolbar
    = f.button :submit, class: 'btn-primary'
    = link_to 'Cancel', collection_path, class: 'btn btn-default'
  = f.input :address
  = f.input :opening_at
  = f.input :closing_at

app/views/admin/shops/index.html.slim
h3 Shops
.well.btn-toolbar
  = link_to 'new', new_resource_path, class: 'btn btn-primary'
  = link_to 'Cancel', admin_chains_path, class: 'btn btn-default'
= table_for collection, html: { class: 'table table-bordered' } do
  - column :id
  - column :address
  - column :opening_at
  - column :closing_at
  - column :created_at
  - column :updated_at
  - column title: 'Actions' do |shop|
    - shops_actions(shop)