config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount API => '/'

  namespace :admin do
    root to: 'users#index'
    resources :car_owners do
      resources :cars
      resources :emails
      resources :phones
    end

    resources :chains do
      member do
        post :update_sheet
      end
      resources :shops
      resources :discounts
      resources :sheets
      resources :sheet_settings
    end

    resources :settings, only: [:edit, :update]
  end

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id                  :integer          not null, primary key
#  model               :string
#  registration_number :string
#  car_owner_id        :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Car < ActiveRecord::Base
  belongs_to :car_owner
end

app/views/admin/cars/_form.html.slim
= simple_form_for [:admin, parent, resource], html: { class: 'form-horizontal' },
                            wrapper: :horizontal_form do |f|
  .well.btn-toolbar
    = f.button :submit, class: 'btn-primary'
    = link_to 'Cancel', collection_path, class: 'btn btn-default'
  = f.input :model
  = f.input :registration_number

app/views/admin/cars/edit.html.slim
= render 'form'

app/views/admin/cars/index.html.slim
h3 Cars
.well.btn-toolbar
  = link_to 'new', new_resource_path, class: 'btn btn-primary'
  = link_to 'Cancel', admin_car_owners_path, class: 'btn btn-default'
= table_for collection, html: { class: 'table table-bordered' } do
  - column :id
  - column :model
  - column :registration_number
  - column :created_at
  - column :updated_at
  - column title: 'Actions' do |car|
    - cars_actions(car)

app/views/admin/cars/new.html.slim
= render 'form'